# Generated by Django 5.1.7 on 2026-02-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateField(null=True),
        ),
    ]
