# Generated by Django 5.1.7 on 2026-02-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_investment"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
