# Generated by Django 5.1.7 on 2026-02-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_transaction_payment_method_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(default="Mpesa", max_length=255),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(default="Pending", max_length=255),
        ),
    ]
