# Generated by Django 5.1.7 on 2026-02-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_moneyrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneyrequest",
            name="from_whom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
