# Generated by Django 5.1.7 on 2026-02-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_moneyrequest_from_whom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moneyrequest",
            name="reason",
        ),
    ]
