# Generated by Django 5.1.7 on 2026-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_remove_moneyrequest_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneyrequest",
            name="reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
