# Generated by Django 5.1.7 on 2026-02-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingeventtype",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="bookingeventtype",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
