# Generated by Django 5.1.7 on 2026-02-22 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_bookingeventtype_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingeventtype",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
