# Generated by Django 5.1.7 on 2026-02-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_eventbooking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventbooking",
            name="status",
            field=models.CharField(default="Pending", max_length=255),
        ),
    ]
