# Generated by Django 5.1.7 on 2026-02-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0007_alter_availabilityslot_day_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabilityslot",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="availabilityslot",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
