# Generated by Django 5.1.7 on 2026-02-24 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0008_alter_availabilityslot_end_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilityslot",
            name="event_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_slots",
                to="scheduling.bookingeventtype",
            ),
        ),
        migrations.AlterField(
            model_name="availabilityslot",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_slots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
