# Generated by Django 5.1.7 on 2026-02-24 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0009_availabilityslot_event_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventbooking",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="scheduling.bookingeventtype",
            ),
        ),
    ]
