# Generated by Django 5.1.7 on 2026-02-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="notes",
        ),
        migrations.AlterField(
            model_name="loan",
            name="direction",
            field=models.CharField(
                choices=[("Borrowed", "Borrowed"), ("Lent", "Lent")], max_length=10
            ),
        ),
    ]
