# Generated by Django 5.1.7 on 2026-02-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_remove_loan_notes_alter_loan_direction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loantransaction",
            name="description",
        ),
    ]
