# Generated by Django 5.1.7 on 2026-02-13 20:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("78c3f8e7-69d2-45b9-a58d-66ab7fc0860d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
