# Generated by Django 5.1.7 on 2026-02-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_link",
            field=models.URLField(null=True),
        ),
    ]
